@startuml
Client -> Server: Authentication Request
Server --> Client: Authentication Response
  

Client -> Server: Another authentication Request
Server <-- Client: another authentication Response
@enduml


@startum1
participant Participant as Foo
actor       Actor       as Foo1
boundary    Boundary    as Foo2
control     Control     as Foo3
entity      Entity      as Foo4
database    Database    as Foo5
collections Collections as Foo6
queue       Queue       as Foo7
Foo -> Foo1 : To actor
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7 : To queue
@enduml



@startum1
actor Bob #Red

participant Alice
participant "У меня очень\подлинное имя" as L #99FF99

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->L: Log transaction
@endum1

@startum1
participant Last order 30
participant Middle order 20
participant First order 10
@endum1


@startum1
Alice -> Alice: Это сигнал к самому себе.\nТакже это является демонстрацией\многострочного \nтекста.
@endum1


@starum1
skinparam sequenceMessageAlign right
Bob->Alice : Request
Alice->Bob : Response
@endum1


@startum1
skinparam responseMessageBelowArrow true
Bob->Alice : дай пять евро
Alice->Bob : нет, не дам
@endum1


@startum1
Bob ->x Alice
Bob -> Alice
Bob ->> Alice
Bob -\ Alice
Bob \\- Alice
Bob //-- Alice

Bob <-> Alice
Bob <->o Alice
@enduml



@startum1
Bob - [#red]> Alice : hello
Alice - [#0000FF]->Bob : ok
@endum1



@startum1
autonumber 1.1.1
Alice -> Bob: Authentication request
Bob --> Alice: Response

autonumber inc A
Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc B 
Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc A 
Alice -> Bob: Another authentication request
autonumber inc B 
Bob --> Alice: Reponse
@endum1




@startum1

Alice -> Bob : message 1
Alice -> Bob : message 2

newpage A title for the\nlast page

Alice -> Bob : message 5
Alice -> Bob : message 6
@endum1

@startum1
Alice -> Bob: Authentication Request

alt successful case 

    Bob -> Alice: Authentication Accepted

else some kind of failure

    Bob -> Alice: Authentication Failure
    group My own label
    Alice -> log : Log attack start
        loop 1000 times 
            Alice -> Bob: DNS Attack
        end
    Alice -> log: Log attack end
    end

else Another type of failure 

    Bob -> Alice: Please repeat

end
@endum1

@startum1
Alice->Bob : привет
note left: это первая заметка

Bob->Bob : я размышляю над этим
note left
заметки 
могут занимать
несколько строчек
end note
@endum1

@startum1
participant Alice
participant Bob
note left of Alice #Aqua
Будет отображено 
слева от Алисы
end note

note right of Alice: Будет отображено справа от Алисы

note over Alice: Будет отображено над Алисой.

note over Alice, Bob #FFAAAA: Будет отображено\n над Алисой и Бобом.

note over Bob, Alice 
А это еще
один пример
длинной заметки.
end note
@endum1

@startum1

== Initialization == 

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

== Repetition == 

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

@endum1

@startum1
Bob -> Alice : привет
activate Alice
Alice -> Alice : какое-то действие
return пока
@endum1

@startum1

title __Simple__ communication example\non several LifelineStrategy

Alice -> Bob: Authentication Request
Bob -> Alice: Authentication Response

@endum1

@startum1

box "Internal Service" #LightBlue
participant Bob
participant Alice
end box
participant Other

Bob -> Alice : hello
Alice -> Other : hello

@endum1

@startum1
Alice -> Bob: zapros avtorizatcii
alt#Gold #LightBlue Успешный кейс
    Bob -> Alice: Запрос удовлетворен
else #Pink Ошибка
    Bob -> Alice: Запрос отклонен
end
@endum1
